### ISSUE TITLE
Does a queue better than attr?

### ISSUE THREAD

**Issue by cliff-ck** [chenyihan/nedis#1]
In the src,All the ResponeAdapter is store in the attr of channel.That is, the channel can do nothing before the response reach.
  Another way is Put ResponeAdapter to a queue and return the channel to the pool asap.
  BTW:I wonder if it need a TIMEOUT setting.

**Comment by chenyihan** [comment]
Thank you for you feedback, I will check your advise.

**Comment by chenyihan** [comment]
It may improve the throughput by returning the channel to pool immediately, but I think we can not put the ResponeAdapters to a queue simply, because it is working in a multi-thread environment, the response may reach later than the other request even its related request is sent earlier, so the ResponeAdapter may be mismatched.

**Comment by chenyihan** [comment]
And the TIMEOUT setting is a option, you can keep it unset if it is considered to be needless.
